name: build

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: "Update draft PDF"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch GitHub metadata
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "TAG_HASH=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "PR_NUMBER=$(gh pr view --json number -q .number)" >> $GITHUB_ENV

      - name: Build draft PDF
        run: |
          nix build
          cp ./result/category-lecture-notes.pdf ./notes-${{ github.sha }}.pdf

      - name: Upload draft PDF
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr
          path: notes-${{ github.sha }}.pdf
          remote_path: www/category-lecture-notes
          remote_host: zamok.crans.org
          remote_port: 22
          remote_user: v-lafeychine
          remote_key: ${{ secrets.DEPLOY_KEY }}

      - name: Update PR with attached draft PDF
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: ci
          message: PDF generation succeeded for ${{ github.sha }}. [Link to PDF](https://perso.crans.org/v-lafeychine/category-lecture-notes/notes-${{ github.sha }}.pdf)
          pr_number: ${{ env.PR_NUMBER }}

      - name: Update PR when failed
        uses: thollander/actions-comment-pull-request@v2
        if: failure()
        with:
          comment_tag: ci
          message: PDF generation failed for ${{ github.sha }}
          pr_number: ${{ env.PR_NUMBER }}
